/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.kozmeticki_salon_klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import rs.ac.bg.fon.ai.kozmeticki_salon_klijent.kontroler.glavni.GlavniKontroler;
/**
 * 
 * Klasa koja predstavlja glavnu formu korisničkog interfejsa aplikacije 
 * za upravljenje radom kozmetičkog salona. Koristi se za prikaz osnovnih informacija i
 * omogućavanje korisnicima pristup različitim funkcionalnostima
 * aplikacije kao što su pregled usluga, klijenata, rezervacija i statistike.
 * 
 * Klasa nasleđuje JFrame i sadrži metode za inicijalizaciju i upravljanje komponentama.
 * 
 * @author Nikolina Baros
 */
public class GlavnaForma extends javax.swing.JFrame {

   
     /**
     * Kreira novu formu GlavnaForma. Konstruktor inicijalizuje
     * komponente korisničkog interfejsa.
     *
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovani = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonOdjava = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kozmeticki salon");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 150));

        jLabelUlogovani.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabelUlogovani.setText(" ");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salon2.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));

        jButtonOdjava.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonOdjava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButtonOdjava.setText("Odjavi se");
        jButtonOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjavaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Dobrodošli,");

        jMenu2.setText("Usluge");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem4.setText("Pregled usluga");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Klijenti");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem2.setText("Pregled klijenata");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Rezervacije");
        jMenu5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem7.setText("Pregled rezervacija");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem1.setText("Statistika rezervacija");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOdjava)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelUlogovani))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Metoda koja se poziva kada korisnik izabere stavku "Pregled klijenata" iz menija.
     * Otvara formu za pregled klijenata.
     * 
     * @param evt Događaj koji izaziva poziv metode.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        GlavniKontroler.getInstance().otvoriPregledKlijenataFormu();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

     /**
     * Metoda koja se poziva kada korisnik izabere stavku "Pregled usluga" iz menija.
     * Otvara formu za pregled usluga.
     * 
     * @param evt Događaj koji izaziva poziv metode.
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        GlavniKontroler.getInstance().otvoriPregledUslugaFormu();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

      /**
     * Metoda koja se poziva kada korisnik izabere stavku "Pregled rezervacija" iz menija.
     * Otvara formu za pregled rezervacija.
     * 
     * @param evt Događaj koji izaziva poziv metode.
     */
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        GlavniKontroler.getInstance().otvoriPregledRezervacijaFormu();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * Metoda koja se poziva kada korisnik pritisne dugme za odjavu.
    
     * @param evt Događaj koji izaziva poziv metode.
     */
    private void jButtonOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOdjavaActionPerformed
/**
     * Metoda koja se poziva kada korisnik izabere stavku "Statistika" iz menija.
     * Otvara formu za pregled statistika.
     * 
     * @param evt Događaj koji izaziva poziv metode.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           GlavniKontroler.getInstance().otvoriStatistikaRezervacijaFormu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdjava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables

    /**
     * Vraća JLabel za prikaz trenutno ulogovanog klijenta.
     *
     * @return JLabel za prikaz trenutno ulogovanog klijenta.
     */
    public JLabel getjLabelUlogovani() {
        return jLabelUlogovani;
    }

      /**
     * Postavlja JLabel za prikaz trenutno ulogovanog klijenta.
     *
     * @param jLabelUlogovani Novi JLabel za prikaz trenutno ulogovanog klijenta.
     */
    public void setjLabelUlogovani(JLabel jLabelUlogovani) {
        this.jLabelUlogovani = jLabelUlogovani;
    }

    /**
     * Dodaje ActionListener za dugme za odjavu klijenta.
     *
     * @param actionListener ActionListener koji će biti dodat dugmetu.
     */
    public void logoutAddActionListener(ActionListener actionListener) {

        jButtonOdjava.addActionListener(actionListener);
    }

}
