/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.kozmeticki_salon_klijent.forme;

import rs.ac.bg.fon.ai.kozmeticki_salon_zajednicki.domen.*;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Klasa koja predstavlja JFrame koji pruža korisnički interfejs za pregled
 * usluga.
 *
 * @author Nikolina Baros
 */
@SuppressWarnings("unused") 
public class PregledUslugaForma extends javax.swing.JFrame {

    /**
     * Kreira novu formu PregledUslugaForma. Konstruktor inicijalizuje
     * komponente korisničkog interfejsa i podešava ponašanje prozora prilikom
     * zatvaranja.
     *
     */
    public PregledUslugaForma() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipovi = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsluge = new javax.swing.JTable();
        jButtonDodajUslugu = new javax.swing.JButton();
        jButtonPrikazUsluge = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretrazivanje usluga po nazivu i tipu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Naziv");

        jTextFieldNaziv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Tip usluge");

        jComboBoxTipovi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jButtonPretrazi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonPretrazi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButtonPretrazi.setText("Pretrazi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonPretrazi)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTableUsluge.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTableUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsluge);

        jButtonDodajUslugu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonDodajUslugu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonDodajUslugu.setText("Dodaj novu uslugu");

        jButtonPrikazUsluge.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonPrikazUsluge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jButtonPrikazUsluge.setText("   Detalji o usluzi");
        jButtonPrikazUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikazUslugeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText(" Usluge");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonDodajUslugu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPrikazUsluge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonDodajUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPrikazUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda koja se poziva kada korisnik klikne na dugme za prikaz detalja o
     * usluzi.
     *
     * @param evt događaj klika na dugme
     */
    private void jButtonPrikazUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikazUslugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikazUslugeActionPerformed

    /**
     * Vraća tabelu sa listom svih usluga.
     *
     * @return JTable sa listom usluga.
     */
    public JTable getjTableUsluge() {
        return jTableUsluge;
    }

    /**
     * Postavlja tabelu sa listom svih usluga.
     *
     *
     * @param jTableUsluge Nova JTable za prikaz liste usluga.
     */
    public void setjTableUsluge(JTable jTableUsluge) {
        this.jTableUsluge = jTableUsluge;
    }

    /**
     * Vraća dugme za pretrazivanje usluga.
     *
     * @return JButton dugme za pretrazivanje usluga.
     */
    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    /**
     * Postavlja dugme za pretrazivanje usluga.
     *
     * @param jButtonPretrazi Novo dugme za pretrazivanje usluga.
     */
    public void setjButtonPretrazi(JButton jButtonPretrazi) {
        this.jButtonPretrazi = jButtonPretrazi;
    }

    /**
     * Vraća JComboBox za izbor tipa usluge.
     *
     * @return JComboBox za izbor tipa usluge.
     */
    public JComboBox<TipUsluge> getjComboBoxTipovi() {
        return jComboBoxTipovi;
    }

    /**
     * Postavlja JComboBox za izbor tipa usluge.
     *
     * @param jComboBoxTipovi Novi JComboBox za izbor tipa usluge.
     */
    public void setjComboBoxTipovi(JComboBox<TipUsluge> jComboBoxTipovi) {
        this.jComboBoxTipovi = jComboBoxTipovi;
    }

    /**
     * Vraća tekstualno polje za unos naziva usluge.
     *
     * @return JTextField za unos naziva usluge.
     */
    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    /**
     * Postavlja tekstualno polje za unos naziva usluge.
     *
     * @param jTextFieldNaziv Novo tekstualno polje za unos naziva usluge.
     */
    public void setjTextFieldNaziv(JTextField jTextFieldNaziv) {
        this.jTextFieldNaziv = jTextFieldNaziv;
    }

    /**
     * Vraća dugme za dodavanje nove usluge.
     *
     * @return JButton dugme za dodavanje nove usluge.
     */
    public JButton getjButtonDodajUslugu() {
        return jButtonDodajUslugu;
    }

    /**
     * Postavlja dugme za dodavanje nove usluge.
     *
     * @param jButtonDodajUslugu Novo dugme za dodavanje nove usluge.
     */
    public void setjButtonDodajUslugu(JButton jButtonDodajUslugu) {
        this.jButtonDodajUslugu = jButtonDodajUslugu;
    }

    /**
     * Vraća dugme za prikaz usluge.
     *
     * @return JButton dugme za prikaz usluge.
     */
    public JButton getjButtonPrikazUsluge() {
        return jButtonPrikazUsluge;
    }

    /**
     * Postavlja dugme za prikaz usluge.
     *
     * @param jButtonPrikazUsluge Novo dugme za prikaz usluge.
     */
    public void setjButtonPrikazUsluge(JButton jButtonPrikazUsluge) {
        this.jButtonPrikazUsluge = jButtonPrikazUsluge;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDodajUslugu;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikazUsluge;
    private javax.swing.JComboBox<TipUsluge> jComboBoxTipovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsluge;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    /**
     * Dodaje ActionListener na dugme za pretragu usluga.
     *
     * @param actionListener ActionListener koji će biti dodat dugmetu.
     */
    public void addButtonPretraziActionListener(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }

    /**
     * Dodaje ActionListener na dugme za prikaz usluge.
     *
     * @param actionListener ActionListener koji će biti dodat dugmetu.
     */
    public void addButtonPrikazUslugeActionListener(ActionListener actionListener) {
        jButtonPrikazUsluge.addActionListener(actionListener);
    }

    /**
     * Dodaje ActionListener na dugme za dodavanje nove usluge.
     *
     * @param actionListener ActionListener koji će biti dodat dugmetu.
     */
    public void addButtonDodajUsluguActionListener(ActionListener actionListener) {
        jButtonDodajUslugu.addActionListener(actionListener);
    }

}
